### ISSUE TITLE
Kursdaten

### ISSUE THREAD

**Issue by marceljakobs** [StegSchreck/HistoricMarketPriceDownloader#4]
Hallo, 
das Programm lädt immer die Tiefstkurse herunter. In der Datei ariva.py in Zeile 174 sollte statt [3] stehen [4], um den close-Kurs zu sehen. Dann erhält man auch z. B. beim DAX über alle Tage bis 1970 Kurse. 

Freundliche Grüße
Marcel

**Comment by StegSchreck** [comment]
Danke für den Hinweis, es ist jetzt gefixed
